name: 11 Custom Actions - Composite

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Node
        uses: ./.github/actions/composite-deps
        with:
          node-version: 20.x # Versión de Node.js especificada
          working-directory: my-app 